import {
  Balcony,
  BreakerPanel,
  Door,
  Lounger,
  Outlet,
  Parasol,
  Pipe,
  Slab,
  Story,
  useStories,
  Wall,
  Wire,
  Window,
} from '@declit/core';
import HotelRoom from './HotelRoom';

const T = 0.28; // exterior wall thickness
const P = 0.12; // partition thickness

/**
 * One guest storey: a double-loaded corridor with `roomsPerSide` rooms on each
 * side. Windows, doors, party walls, ensuite bathrooms, balconies, furniture
 * AND the electrical and plumbing are all generated by mapping over the room
 * index.
 * Because every guest floor renders this same component, the whole floor —
 * services included — is identical on every storey by construction.
 */
export default function GuestFloor({
  level,
  roomsPerSide,
  roomW,
  band = 5,
  corridor = 2,
}: {
  level: number;
  roomsPerSide: number;
  roomW: number;
  band?: number;
  corridor?: number;
}) {
  const { storyHeight } = useStories();
  const L = roomsPerSide * roomW;
  const D = band * 2 + corridor;
  const csouth = band; // z of the south corridor wall
  const cnorth = band + corridor; // z of the north corridor wall
  const ceiling = 2.7;
  const rooms = Array.from({ length: roomsPerSide }, (_, i) => i);
  const center = (i: number) => (i + 0.5) * roomW; // along the south/corridor walls
  const mirror = (i: number) => L - (i + 0.5) * roomW; // along the north walls (reversed direction)
  // wire drops hug the room's west party wall (room 0 hugs the west exterior wall)
  const dropX = (i: number) => (i === 0 ? 0.19 : i * roomW + 0.1);

  return (
    <Story level={level}>
      <Slab id={`h${level}-floor`} outline={[[-0.5, -0.5], [L + 0.5, -0.5], [L + 0.5, D + 0.5], [-0.5, D + 0.5]]} thickness={0.3} />

      {/* south exterior wall — a window, a balcony door and an outlet per south room */}
      <Wall id={`h${level}-south`} from={[0, 0]} to={[L, 0]} thickness={T}>
        {rooms.map((i) => (
          <Window key={i} id={`h${level}-s-win-${i}`} at={center(i)} width={1.6} sill={0.85} height={1.4} />
        ))}
        {rooms.map((i) => (
          <Door key={i} id={`h${level}-s-bdoor-${i}`} at={i * roomW + 3.5} width={0.8} height={2.05} open={0.15} />
        ))}
        {rooms.map((i) => (
          <Outlet key={i} id={`h${level}-s-out-${i}`} at={i * roomW + 0.6} height={0.3} />
        ))}
      </Wall>
      {/* north exterior wall — a window, a balcony door and an outlet per north room */}
      <Wall id={`h${level}-north`} from={[L, D]} to={[0, D]} thickness={T}>
        {rooms.map((i) => (
          <Window key={i} id={`h${level}-n-win-${i}`} at={mirror(i)} width={1.6} sill={0.85} height={1.4} />
        ))}
        {rooms.map((i) => (
          <Door key={i} id={`h${level}-n-bdoor-${i}`} at={L - (i * roomW + 3.5)} width={0.8} height={2.05} open={0.15} />
        ))}
        {rooms.map((i) => (
          <Outlet key={i} id={`h${level}-n-out-${i}`} at={L - (i * roomW + 0.6)} height={0.3} />
        ))}
      </Wall>
      {/* west wall opens onto the circulation core's elevator lobby */}
      <Wall id={`h${level}-west`} from={[0, D]} to={[0, 0]} thickness={T}>
        <Door id={`h${level}-core-door`} at={D - band - corridor / 2} width={1.4} height={2.2} open={0.3} />
      </Wall>
      {/* east wall is the pool side: the two end rooms get balcony doors */}
      <Wall id={`h${level}-east`} from={[L, 0]} to={[L, D]} thickness={T}>
        <Door id={`h${level}-e-bdoor-s`} at={2.5} width={0.9} height={2.05} open={0.15} />
        <Door id={`h${level}-e-bdoor-n`} at={D - 2.5} width={0.9} height={2.05} open={0.15} />
      </Wall>

      {/* corridor walls — one door per room, plus the floor's breaker panel */}
      <Wall id={`h${level}-corr-s`} from={[0, csouth]} to={[L, csouth]} thickness={P} color="#e7e1d4">
        <BreakerPanel id={`h${level}-breaker`} at={0.45} height={1.5} face={1} />
        {rooms.map((i) => (
          <Door key={i} id={`h${level}-s-door-${i}`} at={center(i)} width={0.9} height={2.05} open={0.12} />
        ))}
      </Wall>
      <Wall id={`h${level}-corr-n`} from={[L, cnorth]} to={[0, cnorth]} thickness={P} color="#e7e1d4">
        {rooms.map((i) => (
          <Door key={i} id={`h${level}-n-door-${i}`} at={mirror(i)} width={0.9} height={2.05} open={0.12} />
        ))}
      </Wall>

      {/* party walls between neighboring rooms, both bands */}
      {rooms.slice(1).map((i) => (
        <Wall key={`ps${i}`} id={`h${level}-party-s-${i}`} from={[i * roomW, 0]} to={[i * roomW, csouth]} thickness={P} color="#e7e1d4" />
      ))}
      {rooms.slice(1).map((i) => (
        <Wall key={`pn${i}`} id={`h${level}-party-n-${i}`} from={[i * roomW, cnorth]} to={[i * roomW, D]} thickness={P} color="#e7e1d4" />
      ))}

      {/*
        Electrical: the core riser feeds this floor's breaker panel through the
        west wall; the panel feeds a ceiling ring inside the corridor; each room
        taps the ring, punches through the corridor wall, follows its party wall
        at ceiling height, and drops down the exterior wall to the outlet.
        Every run hugs a wall — nothing crosses open floor.
      */}
      <Wire
        id={`h${level}-feed`}
        points={[
          [-0.18, ceiling, 6.9],
          [0.19, ceiling, 6.9],
          [0.19, ceiling, csouth + 0.1],
          [0.45, ceiling, csouth + 0.1],
          [0.45, 1.78, csouth + 0.1],
        ]}
      />
      <Wire
        id={`h${level}-ring`}
        points={[
          [0.19, ceiling, csouth + 0.1],
          [L - 0.4, ceiling, csouth + 0.1],
          [L - 0.4, ceiling, cnorth - 0.1],
          [0.19, ceiling, cnorth - 0.1],
          [0.19, ceiling, csouth + 0.1],
        ]}
      />
      {rooms.map((i) => (
        <Wire
          key={`ws${i}`}
          id={`h${level}-drop-s-${i}`}
          points={[
            [dropX(i), ceiling, csouth + 0.1],
            [dropX(i), ceiling, csouth - 0.06],
            [dropX(i), ceiling, 0.19],
            [dropX(i), 0.3, 0.19],
            [i * roomW + 0.6, 0.3, 0.19],
          ]}
        />
      ))}
      {rooms.map((i) => (
        <Wire
          key={`wn${i}`}
          id={`h${level}-drop-n-${i}`}
          points={[
            [dropX(i), ceiling, cnorth - 0.1],
            [dropX(i), ceiling, cnorth + 0.06],
            [dropX(i), ceiling, D - 0.19],
            [dropX(i), 0.3, D - 0.19],
            [i * roomW + 0.6, 0.3, D - 0.19],
          ]}
        />
      ))}

      {/*
        Plumbing: cold + hot risers climb the wet wall at the west end of each
        room band (boxed in a duct on the ground floor), continuous up the
        building. Supply branches run under this slab along the corridor walls
        and every bathroom taps them through the floor (see HotelRoom). The WC
        and basin drains drop to a soil collector under each bathroom line,
        which falls back to a soil stack beside the risers.
      */}
      {[
        { tag: 's', wall: csouth, sgn: -1 },
        { tag: 'n', wall: cnorth, sgn: 1 },
      ].map(({ tag, wall, sgn }) => (
        <group key={tag}>
          {/* risers, continuous with the segments below and above */}
          <Pipe id={`h${level}-${tag}-riser-cold`} color="#3e7fb2" points={[[0.24, 0, wall + sgn * 0.1], [0.24, storyHeight, wall + sgn * 0.1]]} />
          <Pipe id={`h${level}-${tag}-riser-hot`} color="#b87333" points={[[0.38, 0, wall], [0.38, storyHeight, wall]]} />
          <Pipe id={`h${level}-${tag}-soil-stack`} color="#8f969e" radius={0.05} points={[[0.52, 0, wall + sgn * 0.45], [0.52, storyHeight, wall + sgn * 0.45]]} />
          {/* under-slab supply branches along the corridor wall */}
          <Pipe id={`h${level}-${tag}-branch-cold`} color="#3e7fb2" points={[[0.24, -0.42, wall + sgn * 0.1], [L - 2.8, -0.42, wall + sgn * 0.1]]} />
          <Pipe id={`h${level}-${tag}-branch-hot`} color="#b87333" points={[[0.38, -0.42, wall], [L - 2.8, -0.42, wall]]} />
          {/* soil collector under the bathroom line, falling to the stack */}
          <Pipe id={`h${level}-${tag}-collector`} color="#8f969e" radius={0.05} points={[[0.4, -0.42, wall + sgn * 0.9], [L - 2.9, -0.42, wall + sgn * 0.9]]} />
          <Pipe id={`h${level}-${tag}-collector-out`} color="#8f969e" radius={0.05} points={[[0.52, -0.42, wall + sgn * 0.45], [0.52, -0.42, wall + sgn * 0.9]]} />
        </group>
      ))}

      {/* rooms: ensuite + furniture, one per side per bay */}
      {rooms.map((i) => (
        <HotelRoom key={`rs${i}`} tag={`h${level}-s${i}`} at={[i * roomW, 0]} width={roomW} depth={band} facing="south" />
      ))}
      {rooms.map((i) => (
        <HotelRoom key={`rn${i}`} tag={`h${level}-n${i}`} at={[i * roomW, cnorth]} width={roomW} depth={band} facing="north" />
      ))}

      {/* balconies: every room gets one off its balcony door, furnished with a
          şezlong and a parasol; the east end rooms get pool-view balconies
          through the otherwise solid east wall */}
      {rooms.map((i) => (
        <group key={`bs${i}`}>
          <Balcony id={`h${level}-s-balc-${i}`} at={[i * roomW + 2.5, -1.5]} width={1.6} depth={1.5} open="north" />
          <Lounger id={`h${level}-s-lounger-${i}`} at={[i * roomW + 3.0, -0.78]} facing="south" />
          <Parasol id={`h${level}-s-parasol-${i}`} at={[i * roomW + 3.8, -0.95]} />
        </group>
      ))}
      {rooms.map((i) => (
        <group key={`bn${i}`}>
          <Balcony id={`h${level}-n-balc-${i}`} at={[i * roomW + 2.5, D]} width={1.6} depth={1.5} open="south" />
          <Lounger id={`h${level}-n-lounger-${i}`} at={[i * roomW + 3.0, D + 0.78]} facing="north" />
          <Parasol id={`h${level}-n-parasol-${i}`} at={[i * roomW + 3.8, D + 0.95]} />
        </group>
      ))}
      <Balcony id={`h${level}-e-balc-s`} at={[L, 1.6]} width={1.8} depth={1.8} open="west" />
      <Lounger id={`h${level}-e-lounger-s`} at={[L + 1.0, 2.3]} facing="east" />
      <Parasol id={`h${level}-e-parasol-s`} at={[L + 1.3, 3.0]} />
      <Balcony id={`h${level}-e-balc-n`} at={[L, D - 3.4]} width={1.8} depth={1.8} open="west" />
      <Lounger id={`h${level}-e-lounger-n`} at={[L + 1.0, D - 2.1]} facing="east" />
      <Parasol id={`h${level}-e-parasol-n`} at={[L + 1.3, D - 3.0]} />
    </Story>
  );
}
